### PR TITLE
Eslint support

### PR DESCRIPTION
**Pull request by Weredime**
Eslint style guide stuff

### CODE REVIEW

**Comment by Looky1173** [comment]
Why are apostrophe replaced with `&apos;`?

**Comment by Weredime** [comment]
> Why are apostrophes replaced with `&apos;`?

There's an eslint rule for disallowing it. The recommended standard is using `&apos;` (replacement for apostrophes) in React JSX.

**Comment by Looky1173** [comment]
Could we disable this specific ESLint rule? I don't see how plain apostrophes would be a problem...

**Comment by Weredime** [comment]
It could also affect the string initializer '

**Pull request merged**
